roles:
  supervisor: openai/gpt-4o
  planner: google/gemini-flash-1.5
  coder: openai/gpt-4o
  critic: google/gemini-flash-1.5
  context: google/gemini-flash-1.5

fallbacks:
  supervisor: google/gemini-flash-1.5
  planner: google/gemini-flash-1.5
  coder: google/gemini-flash-1.5
  critic: google/gemini-flash-1.5
  context: google/gemini-flash-1.5
