roles:
  supervisor: anthropic/claude-3.5-sonnet
  planner: anthropic/claude-3.5-sonnet
  coder: anthropic/claude-3.5-sonnet
  critic: anthropic/claude-3.5-sonnet

fallbacks:
  supervisor: anthropic/claude-3.5-sonnet
  planner: anthropic/claude-3.5-sonnet
  coder: anthropic/claude-3.5-sonnet
  critic: anthropic/claude-3.5-sonnet

embedding_models:
  default: voyage-3.5
  large: voyage-3-large
  code: voyage-code-3
